# version: "3.8"
services:
  # aplikasi nodejs wa gateway
  gateway2:
    container_name: stie-wa-gateway2
    image: ghcr.io/mfth12/wa-gateway2-stie:latest
    environment:
      - PORT=${PORT}
      - KEY=${KEY}
    # working_dir: /app
    volumes:
      # - gtwdata:/app
      - ./wa_credentials:/wa_credentials
    # network_mode: host
    ports:
      - 8180:8180
    networks:
      - wa-gateway
    restart: always

# mengatur volumes
volumes:
  gtwdata:
    driver: local

#setup jaringan
networks:
  wa-gateway:
    driver: bridge
