# version: "3.8"
services:
  # aplikasi nodejs wa gateway
  gateway:
    container_name: stie-wa-gateway2
    image: ghcr.io/mfth12/wa-gateway2-stie:latest
    environment:
      - PORT=${PORT}
      - KEY=${KEY}
    working_dir: /gateway2
    volumes:
      - gtwdata:/gateway2
      - ./wa_credentials:/gateway2/wa_credentials
      # - ./session:/gateway2/session
    # network_mode: host
    ports:
      - 8180:8180
    restart: always
    networks:
      - wa-gateway

# mengatur volumes
volumes:
  gtwdata:
    driver: local

#setup jaringan
networks:
  wa-gateway:
    driver: bridge
